import React from "react";
import Image from "next/image";
import Head from "next/head";
import Header from "@/components/header";
import { Icon } from "@iconify/react";
import {
  IntroContent,
  AboutUs,
  Ads,
  Expertise,
  Objectives,
  Services,
  Partners,
  Blog,
  Newsletter,
} from "@/components/Home";

export default function Home() {
  const [showTopBtn, setShowTopBtn] = React.useState(false);
  const [isOpen, setIsOpen] = React.useState(false);

  React.useEffect(() => {
    window.addEventListener("scroll", () => {
      if (window.scrollY > 400) {
        setShowTopBtn(true);
      } else {
        setShowTopBtn(false);
      }
    });
  });

  return (
    <>
      <Head>
        <title>Cyberroot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header isOpen={isOpen} setIsOpen={setIsOpen} />
        <IntroContent />
        <Ads />
        <Expertise />
        <AboutUs />
        <Objectives />
        <Services />
        <Partners />
        <Blog />
        <Newsletter />
      </main>
    </>
  );
}
