export const HOME = "/";
export const CYBERROOTSUMMIT = "https://summit.cyberrootltd.com/";
export const BLOG = "/blog";
export const TRAINING = "/training";
export const CONTACT_US = "/contact-us";
export const ABOUT_US = "/about-us";
export const SERVICES = "/services/threat-assessment";
export const SERVICES_PAGES = (url) => "/services/" + url;
export const BLOG_PAGES = (url) => "/blog/" + url;
export const EVENT_PAGES = (url) => "/events/" + url;
